name: Rust

on:
  pull_request:
  merge_group:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
