name: Rust

on:
  pull_request:
  merge_group:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
    - name: Clippy
      run: cargo clippy -- -D warnings
    - name: Build
      run: make build
    - name: cargo test --locked
      run: cargo test --locked --all-features --all-targets
    # https://github.com/rust-lang/cargo/issues/6669
    - name: cargo test --doc
      run: cargo test --locked --all-features --doc
    - name: Run e2e
      run: |
        bash ./tests/e2e/test_basic_tcp.sh
        bash ./tests/e2e/test_tcp_local_server_not_start.sh
        bash ./tests/e2e/test_close_server_gracefully.sh
        bash ./tests/e2e/test_tcp_with_tunnel_http_server.sh
        bash ./tests/e2e/test_http_tunnel_with_domain.sh
        bash ./tests/e2e/test_http_tunnel_with_subdomain.sh
        bash ./tests/e2e/test_http_tunnel_with_given_port.sh
