name: Rust

on:
  pull_request:
  merge_group:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
    - name: Install dependencies
      run: sudo apt-get install -y socat 
    - name: Clippy
      run: cargo clippy -- -D warnings
    - name: Build
      run: make build
    - name: unit test
      run: cargo test --locked --all-targets
    # https://github.com/rust-lang/cargo/issues/6669
    - name: doc test
      run: cargo test --locked --all-features --doc
    - name: e2e test
      run: make e2e
  go-sdk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
    - name: Install dependencies
      run: sudo apt-get install -y socat 
    - name: go vet
      run: go vet ./...
    - name: go test
      run: go test -v ./...
    - name: e2e with go client
      run: make e2e CLIENT_BINARY=$PWD/tests/e2e/.bin/castlego E2E_TEST_UDP=0
  run-examples:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: examples test
      run: make test-examples
