name: Rust

on:
  pull_request:
  merge_group:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Clippy
      run: cargo clippy -- -D warnings
    - name: Build
      run: make build
    - name: cargo test --locked
      run: cargo test --locked --all-targets
    # https://github.com/rust-lang/cargo/issues/6669
    - name: cargo test --doc
      run: cargo test --locked --all-features --doc
    - name: Run e2e
      run: make e2e
