name: Create Tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: "New tag"
        required: true
        default: "v0.0.1(match the version in Cargo.toml)"

jobs:
  create-tag:
    name: create-tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      # GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_TOKEN: ${{ secrets.PAT_FOR_TAG }}
    steps:
      - uses: actions/checkout@v4
        with:
          # use personal access token to create tag to it can trigger other workflows
          token: ${{ secrets.PAT_FOR_TAG }}
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ github.event.inputs.version }}',
              sha: context.sha
            })
